---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: [24, 25, 26]
        elixir: ['1.15.6', '1.15.5']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_vsn}}
          elixir-version: ${{matrix.elixir}}
          rebar3-version: '3.22.1'
      - run: rebar3 xref
        # - run: rebar3 dialyzer
      - run: cd example && rebar3 eunit
